repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json
        exclude: ".*\\.vscode/"
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: debug-statements
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/python-poetry/poetry
    rev: 2.2.1
    hooks:
      - id: poetry-check
        args: ["--lock"]

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.2.0
    hooks:
    -   id: add-trailing-comma

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: Run mypy
        entry: inv mypy.run
        language: system
        pass_filenames: false
        types: [ file ]
        stages: [ pre-push ]

      - id: pytest
        name: Run pytest
        entry: inv pytest.run -p="--cov=."
        language: system
        pass_filenames: false
        types: [ file ]
        stages: [ pre-push ]
